### ISSUE TITLE
Fails to Install on OS X 10.11 with Error

### ISSUE THREAD

**Issue by TaylorSMarks** [msanders/autopy#75]
When I do

```
sudo pip install autopy
```

I fail with 10 warnings and 9 errors. The warnings are all about stuff that was deprecated in 10.6. The errors are as follows:

```
src/screengrab.c:194:15: error: use of undeclared identifier 'GL_FRONT'
            glReadBuffer(GL_FRONT);
                         ^

src/screengrab.c:199:22: error: use of undeclared identifier 'GL_NO_ERROR'
        if (glGetError() != GL_NO_ERROR) return NULL;
                            ^

src/screengrab.c:223:21: error: use of undeclared identifier 'GL_CLIENT_PIXEL_STORE_BIT'
        glPushClientAttrib(GL_CLIENT_PIXEL_STORE_BIT);
                           ^

src/screengrab.c:225:16: error: use of undeclared identifier 'GL_PACK_ALIGNMENT'
        glPixelStorei(GL_PACK_ALIGNMENT, BYTE_ALIGN); /* Force alignment. */
                      ^

src/screengrab.c:226:16: error: use of undeclared identifier 'GL_PACK_ROW_LENGTH'
        glPixelStorei(GL_PACK_ROW_LENGTH, 0);
                      ^

src/screengrab.c:227:16: error: use of undeclared identifier 'GL_PACK_SKIP_ROWS'
        glPixelStorei(GL_PACK_SKIP_ROWS, 0);
                      ^

src/screengrab.c:228:16: error: use of undeclared identifier 'GL_PACK_SKIP_PIXELS'
        glPixelStorei(GL_PACK_SKIP_PIXELS, 0);
                      ^

src/screengrab.c:236:30: error: use of undeclared identifier 'GL_BGRA'
                     MMRGB_IS_BGR ? GL_BGRA : GL_RGBA,
                                    ^

src/screengrab.c:240:15: error: use of undeclared identifier 'GL_UNSIGNED_INT_8_8_8_8_REV'
                     GL_UNSIGNED_INT_8_8_8_8_REV, /* Native format */
                     ^
```

**Comment by elyase** [comment]
I am getting this on 10.10 with the Anaconda python distribution.

**Comment by elyase** [comment]
Got it working on 10.11 with:

    brew install libpng
    CFLAGS="-Wno-return-type" pip install git+https://github.com/potpath/autopy.git

**Comment by TaylorSMarks** [comment]
I attempted to follow your directions, but I ended with this error:

    src/png_io.c:3:10: fatal error: 'png.h' file not found
    #include <png.h>
             ^

**Comment by nuty** [comment]
@elyase  it worked,  thank you.

**Comment by Saurabhguptacse** [comment]
Not worked on macOS: Sierra: 10.12.4.
Same error thrown which occur with normal pip command. Please help.

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) which includes binary wheel distributions.
